name: memberorg-app
region: sfo

# Dev Database (Free tier)
databases:
  - name: memberorg-db
    engine: PG
    version: "15"
    production: false
    size: db-s-dev-database
  
# C# API Service
services:
  - name: api
    dockerfile_path: apps/api/Dockerfile
    source_dir: apps/api
    github:
      repo: adilp/BCFR
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
    - path: /api
    envs:
    - key: DATABASE_URL
      scope: RUN_TIME
      value: ${memberorg-db.DATABASE_URL}
    - key: ASPNETCORE_ENVIRONMENT
      scope: RUN_TIME
      value: Production
    - key: CORS_ORIGINS
      scope: RUN_TIME
      value: ${APP_URL}
  
# React Web App
static_sites:
  - name: web
    source_dir: apps/web
    github:
      repo: adilp/BCFR
      branch: main
      deploy_on_push: true
    build_command: npm install --force && npm run build
    output_dir: dist
    routes:
    - path: /
    envs:
    - key: VITE_API_URL
      scope: BUILD_TIME
      value: ${APP_URL}/api
# Environment variables
envs:
  - key: APP_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}