// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import the generated route tree
import { Route as rootRoute } from './router'

// Create and export the route tree type
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      parentRoute: typeof rootRoute
    }
    '/about': {
      parentRoute: typeof rootRoute
    }
    '/membership': {
      parentRoute: typeof rootRoute
    }
    '/login': {
      parentRoute: typeof rootRoute
    }
    '/register': {
      parentRoute: typeof rootRoute
    }
  }
}

// Export the generated route tree
export const routeTree = rootRoute