DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'memberorg') THEN
        CREATE SCHEMA memberorg;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS memberorg."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'memberorg') THEN
        CREATE SCHEMA memberorg;
    END IF;
END $EF$;

CREATE TABLE memberorg."Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(255) NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON memberorg."Users" ("Email");

INSERT INTO memberorg."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250726191823_InitialCreate', '9.0.0');

ALTER TABLE memberorg."Users" ADD "PasswordHash" text NOT NULL DEFAULT '';

ALTER TABLE memberorg."Users" ADD "Username" character varying(100) NOT NULL DEFAULT '';

CREATE TABLE memberorg."Sessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UserAgent" character varying(500),
    "IpAddress" character varying(45),
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES memberorg."Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Users_Username" ON memberorg."Users" ("Username");

CREATE UNIQUE INDEX "IX_Sessions_Token" ON memberorg."Sessions" ("Token");

CREATE INDEX "IX_Sessions_UserId" ON memberorg."Sessions" ("UserId");

INSERT INTO memberorg."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250809124725_AddAuthentication', '9.0.0');

COMMIT;

